platform :ios, '8.0'

target '移动采集' do

pod 'SDWebImage'
pod 'YYKit'
pod 'YTKNetwork'
pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'LxDBAnything'
pod 'MJRefresh'
pod 'AMScrollingNavbar', '~> 1.5.1’
pod 'TOCropViewController'
pod 'PureLayout'
pod 'Masonry'
pod 'JPush'
pod 'JAnalytics'
pod 'WechatOpenSDK'
pod 'Reachability'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'SocketRocket'
pod 'LKDBHelper'
pod 'ReactiveObjC'
pod 'GPUImage'

end
