//
//  NoticeMacro.h
//  trafficPolice
//
//  Created by hcat-89 on 2017/5/16.
//  Copyright © 2017年 Degal. All rights reserved.
//

#ifndef NoticeMacro_h
#define NoticeMacro_h

#define NOTIFICATION_WX_LOGIN_SUCCESS @"NOTIFICATION_WX_LOGIN_SUCCESS"                          //微信发送成功
#define NOTIFICATION_CHANGELOCATION_SUCCESS @"NOTIFICATION_CHANGELOCATION_SUCCESS"              //定位地址成功

#define NOTIFICATION_NONETWORK_SUCCESS @"NOTIFICATION_NONETWORK_SUCCESS"                        //无网络
#define NOTIFICATION_HAVENETWORK_SUCCESS @"NOTIFICATION_HAVENETWORK_SUCCESS"                    //无网络到有网络的通知

#define NOTIFICATION_WILLPRESENTNOTIFICATION @"NOTIFICATION_WILLPRESENTNOTIFICATION"            //即将展现消息通知

#define NOTIFICATION_RECEIVENOTIFICATION_SUCCESS @"NOTIFICATION_RECEIVENOTIFICATION_SUCCESS"    //接收到通知
#define NOTIFICATION_MAKESURENOTIFICATION_SUCCESS @"NOTIFICATION_MAKESURENOTIFICATION_SUCCESS"  //确认通知
#define NOTIFICATION_COMPLETENOTIFICATION_SUCCESS @"NOTIFICATION_COMPLETENOTIFICATION_SUCCESS"  //完成出警任务
#define NOTIFICATION_COMPLETEOPERATCAR_SUCCESS @"NOTIFICATION_COMPLETEOPERATCAR_SUCCESS"        //非法车辆豁免通知


#define NOTIFICATION_ADDREMARK_SUCCESS @"NOTIFICATION_ADDREMARK_SUCCESS"                        //添加备注成功通知

#define NOTIFICATION_ACCIDENT_SUCCESS @"NOTIFICATION_ACCIDENT_SUCCESS"                          //事故采集提交成功
#define NOTIFICATION_FASTACCIDENT_SUCCESS @"NOTIFICATION_FASTACCIDENT_SUCCESS"                  //快处事故采集提交成功
#define NOTIFICATION_ILLEGALPARK_SUCCESS @"NOTIFICATION_ILLEGALPARK_SUCCESS"                    //违停采集提交成功
#define NOTIFICATION_ILLEGALTHROUGH_SUCCESS @"NOTIFICATION_ILLEGALTHROUGH_SUCCESS"              //闯禁令采集提交成功
#define NOTIFICATION_VIDEO_SUCCESS @"NOTIFICATION_VIDEO_SUCCESS"                                //视频采集提交成功

#define NOTIFICATION_RELOADWATCH_SUCCESS @"NOTIFICATION_RELOADWATCH_SUCCESS"                    //重新刷新值班



#endif /* NoticeMacro_h */
