//
//  UserDefaultMacro.h
//  trafficPolice
//
//  Created by hcat on 2017/5/22.
//  Copyright © 2017年 Degal. All rights reserved.
//

#ifndef UserDefaultMacro_h
#define UserDefaultMacro_h

#define USERDEFAULT_KEY_USERMODEL   @"USERDEFAULT_KEY_USERMODEL"    //用户数据
#define USERDEFAULT_KEY_TOKEN       @"USERDEFAULT_KEY_TOKEN"        //请求token值
#define USERDEFAULT_KEY_PHONE       @"USERDEFAULT_KEY_PHONE"        //用户手机号码
#define USERDEFAULT_KEY_SEARCHTAG   @"USERDEFAULT_KEY_SEARCHTAG"    //搜索下的tag
#define USERDEFAULT_KEY_SERVER_URL  @"USERDEFAULT_KEY_SERVER_URL"   //服务器地址
#define USERDEFAULT_KEY_WEBSOCKET_URL   @"USERDEFAULT_KEY_WEBSOCKET_URL"  //webSocket地址
#define USERDEFAULT_KEY_DUTY @"USERDEFAULT_KEY_DUTY"    //值班通知点
#define USERDEFAULT_KEY_ACTION @"USERDEFAULT_KEY_ACTION" //行动通知点
#define USERDEFAULT_KEY_UPTIME @"USERDEFAULT_KEY_UPTIME" //上传截止时间

#pragma mark -

#define USERDEFAULT_KEY_ISPARK @"USERDEFAULT_KEY_ISPARK"
#define USERDEFAULT_KEY_ISTHROUGH @"USERDEFAULT_KEY_ISTHROUGH"
#define USERDEFAULT_KEY_ISTOWARDERROR @"USERDEFAULT_KEY_ISTOWARDERROR"
#define USERDEFAULT_KEY_ISLOCKCAR @"USERDEFAULT_KEY_ISLOCKCAR"
#define USERDEFAULT_KEY_ISINFORINPUT @"USERDEFAULT_KEY_ISINFORINPUT"
#define USERDEFAULT_KEY_ISVEHICLE @"USERDEFAULT_KEY_ISVEHICLE"

#define USERDEFAULT_KEY_PARK @"USERDEFAULT_KEY_PARK"
#define USERDEFAULT_KEY_THROUGH @"USERDEFAULT_KEY_THROUGH"
#define USERDEFAULT_KEY_TOWARDERROR @"USERDEFAULT_KEY_TOWARDERROR"
#define USERDEFAULT_KEY_LOCKCAR @"USERDEFAULT_KEY_LOCKCAR"
#define USERDEFAULT_KEY_INFORINPUT @"USERDEFAULT_KEY_INFORINPUT"
#define USERDEFAULT_KEY_VEHICLE @"USERDEFAULT_KEY_VEHICLE"


#endif /* UserDefaultMacro_h */
