//
//  UserDefaultMacro.h
//  trafficPolice
//
//  Created by hcat on 2017/5/22.
//  Copyright © 2017年 Degal. All rights reserved.
//

#ifndef UserDefaultMacro_h
#define UserDefaultMacro_h

#define USERDEFAULT_KEY_USERMODEL       @"USERDEFAULT_KEY_USERMODEL"            //用户数据
#define USERDEFAULT_KEY_TOKEN           @"USERDEFAULT_KEY_TOKEN"                //请求token值
#define USERDEFAULT_KEY_PHONE           @"USERDEFAULT_KEY_PHONE"                //用户手机号码
#define USERDEFAULT_KEY_SEARCHTAG       @"USERDEFAULT_KEY_SEARCHTAG"            //搜索下的tag
#define USERDEFAULT_KEY_SERVER_URL      @"USERDEFAULT_KEY_SERVER_URL"           //服务器地址
#define USERDEFAULT_KEY_WEBSOCKET_URL   @"USERDEFAULT_KEY_WEBSOCKET_URL"        //webSocket地址
#define USERDEFAULT_KEY_DUTY            @"USERDEFAULT_KEY_DUTY"                 //值班通知点
#define USERDEFAULT_KEY_ACTION          @"USERDEFAULT_KEY_ACTION"               //行动通知点
#define USERDEFAULT_KEY_UPTIME          @"USERDEFAULT_KEY_UPTIME"               //上传截止时间
#define USERDEFAULT_KEY_UPSTEPTIME      @"USERDEFAULT_KEY_UPSTEPTIME"           //上传步数时间
#define USERDEFAULT_KEY_DAILYPRATROL    @"USERDEFAULT_KEY_DAILYPRATROL"         //巡逻点是否上报


#pragma mark -

#define USERDEFAULT_KEY_ISPARK @"USERDEFAULT_KEY_ISPARK"
#define USERDEFAULT_KEY_ISTHROUGH @"USERDEFAULT_KEY_ISTHROUGH"
#define USERDEFAULT_KEY_ISTOWARDERROR @"USERDEFAULT_KEY_ISTOWARDERROR"
#define USERDEFAULT_KEY_ISLOCKCAR @"USERDEFAULT_KEY_ISLOCKCAR"
#define USERDEFAULT_KEY_ISMOTORBIKE @"USERDEFAULT_KEY_ISMOTORBIKE"
#define USERDEFAULT_KEY_ISINFORINPUT @"USERDEFAULT_KEY_ISINFORINPUT"
#define USERDEFAULT_KEY_ISVEHICLE @"USERDEFAULT_KEY_ISVEHICLE"
#define USERDEFAULT_KEY_ISINHIBITLINE @"USERDEFAULT_KEY_ISINHIBITLINE"
#define USERDEFAULT_KEY_ISTAKEOUT @"USERDEFAULT_KEY_ISTAKEOUT"
#define USERDEFAULT_KEY_ISFORENSICS @"USERDEFAULT_KEY_ISFORENSICS"
#define USERDEFAULT_KEY_ISILLEGALEXPOSURE @"USERDEFAULT_KEY_ISILLEGALEXPOSURE"
#define USERDEFAULT_KEY_ISILLEGAL @"USERDEFAULT_KEY_ISILLEGAL"
#define USERDEFAULT_KEY_ISTHROUGHMANAGE @"USERDEFAULT_KEY_ISTHROUGHMANAGE"
#define USERDEFAULT_KEY_ISSTREET @"USERDEFAULT_KEY_ISSTREET"

#define USERDEFAULT_KEY_PARK @"USERDEFAULT_KEY_PARK"
#define USERDEFAULT_KEY_THROUGH @"USERDEFAULT_KEY_THROUGH"
#define USERDEFAULT_KEY_TOWARDERROR @"USERDEFAULT_KEY_TOWARDERROR"
#define USERDEFAULT_KEY_LOCKCAR @"USERDEFAULT_KEY_LOCKCAR"
#define USERDEFAULT_KEY_MOTORBIKE @"USERDEFAULT_KEY_MOTORBIKE"
#define USERDEFAULT_KEY_INFORINPUT @"USERDEFAULT_KEY_INFORINPUT"
#define USERDEFAULT_KEY_VEHICLE @"USERDEFAULT_KEY_VEHICLE"
#define USERDEFAULT_KEY_INHIBITLINE @"USERDEFAULT_KEY_INHIBITLINE"
#define USERDEFAULT_KEY_TAKEOUT @"USERDEFAULT_KEY_TAKEOUT"
#define USERDEFAULT_KEY_FORENSICS @"USERDEFAULT_KEY_FORENSICS"
#define USERDEFAULT_KEY_ILLEGALEXPOSURE @"USERDEFAULT_KEY_ILLEGALEXPOSURE"
#define USERDEFAULT_KEY_ILLEGAL @"USERDEFAULT_KEY_ILLEGAL"
#define USERDEFAULT_KEY_THROUGHMANAGE  @"USERDEFAULT_KEY_THROUGHMANAGE"
#define USERDEFAULT_KEY_STREET @"USERDEFAULT_KEY_STREET"

#define USERDEFAULT_KEY_ISAUTOPARK @"USERDEFAULT_KEY_ISAUTOPARK"
#define USERDEFAULT_KEY_ISAUTOREVERSEPARK @"USERDEFAULT_KEY_ISAUTOREVERSEPARK"
#define USERDEFAULT_KEY_ISAUTOLOCKPARK @"USERDEFAULT_KEY_ISAUTOLOCKPARK"
#define USERDEFAULT_KEY_ISAUTOCARINFOADD @"USERDEFAULT_KEY_ISAUTOCARINFOADD"
#define USERDEFAULT_KEY_ISAUTOTHROUGH @"USERDEFAULT_KEY_ISAUTOTHROUGH"
#define USERDEFAULT_KEY_ISAUTOACCIDENT @"USERDEFAULT_KEY_ISAUTOACCIDENT"
#define USERDEFAULT_KEY_ISAUTOFASTACCIDENT @"USERDEFAULT_KEY_ISAUTOFASTACCIDENT"
#endif /* UserDefaultMacro_h */
