//
//  UserDefaultMacro.h
//  trafficPolice
//
//  Created by hcat on 2017/5/22.
//  Copyright © 2017年 Degal. All rights reserved.
//

#ifndef UserDefaultMacro_h
#define UserDefaultMacro_h

#define USERDEFAULT_KEY_USERMODEL   @"USERDEFAULT_KEY_USERMODEL"    //用户数据
#define USERDEFAULT_KEY_TOKEN       @"USERDEFAULT_KEY_TOKEN"        //请求token值
#define USERDEFAULT_KEY_PHONE       @"USERDEFAULT_KEY_PHONE"        //用户手机号码
#define USERDEFAULT_KEY_SEARCHTAG   @"USERDEFAULT_KEY_SEARCHTAG"    //搜索下的tag

#pragma mark -

#define USERDEFAULT_KEY_ISPARK @"USERDEFAULT_KEY_ISPARK"
#define USERDEFAULT_KEY_ISTHROUGH @"USERDEFAULT_KEY_ISTHROUGH"
#define USERDEFAULT_KEY_ISTOWARDERROR @"USERDEFAULT_KEY_ISTOWARDERROR"
#define USERDEFAULT_KEY_ISLOCKCAR @"USERDEFAULT_KEY_ISLOCKCAR"
#define USERDEFAULT_KEY_ISINFORINPUT @"USERDEFAULT_KEY_ISINFORINPUT"

#define USERDEFAULT_KEY_PARK @"USERDEFAULT_KEY_PARK"
#define USERDEFAULT_KEY_THROUGH @"USERDEFAULT_KEY_THROUGH"
#define USERDEFAULT_KEY_TOWARDERROR @"USERDEFAULT_KEY_TOWARDERROR"
#define USERDEFAULT_KEY_LOCKCAR @"USERDEFAULT_KEY_LOCKCAR"
#define USERDEFAULT_KEY_INFORINPUT @"USERDEFAULT_KEY_INFORINPUT"


#endif /* UserDefaultMacro_h */
